const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const jwt = require("jsonwebtoken");
const basesDoc = require("../data/bases.json");
const { parseClaimsMail } = require("./claims-mail-parser");

const DATA_FILE = process.env.DATA_FILE || path.join(__dirname, "..", "database.json");
const GMAIL_SCOPE = "https://www.googleapis.com/auth/gmail.modify";
const GMAIL_EXPECTED_ACCOUNT = process.env.GMAIL_ACCOUNT || "asistir24operadores@gmail.com";
const GMAIL_AUTO_ENABLED = String(process.env.GMAIL_AUTO_ENABLED || "").toLowerCase() === "true";
const GMAIL_POLL_MS = Math.max(60000, Number(process.env.GMAIL_POLL_MS || 120000));

function readData() { try { const v = JSON.parse(fs.readFileSync(DATA_FILE, "utf8")); return v && typeof v === "object" ? v : {}; } catch { return {}; } }
function writeData(data) { const temp = DATA_FILE + ".gmail.tmp"; fs.mkdirSync(path.dirname(DATA_FILE), { recursive: true }); fs.writeFileSync(temp, JSON.stringify(data, null, 2)); fs.renameSync(temp, DATA_FILE); }
function jwtSecret() { return process.env.JWT_SECRET || "gmail-runtime-no-jwt"; }
function gmailConfigured() { return Boolean(process.env.GMAIL_CLIENT_ID && process.env.GMAIL_CLIENT_SECRET && process.env.GMAIL_REDIRECT_URI); }
function encryptionKey() { return crypto.createHash("sha256").update("asistir24:gmail:" + jwtSecret()).digest(); }
function encryptSecret(value) { const iv=crypto.randomBytes(12), cipher=crypto.createCipheriv("aes-256-gcm",encryptionKey(),iv), encrypted=Buffer.concat([cipher.update(String(value),"utf8"),cipher.final()]), tag=cipher.getAuthTag(); return [iv.toString("base64url"),tag.toString("base64url"),encrypted.toString("base64url")].join("."); }
function decryptSecret(value) { const [ivText,tagText,encryptedText]=String(value||"").split("."); if(!ivText||!tagText||!encryptedText) throw new Error("Credencial de Gmail inválida"); const decipher=crypto.createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(ivText,"base64url")); decipher.setAuthTag(Buffer.from(tagText,"base64url")); return Buffer.concat([decipher.update(Buffer.from(encryptedText,"base64url")),decipher.final()]).toString("utf8"); }
function readConnection() { const d=readData(); return d.gmail&&typeof d.gmail==="object"?d.gmail:null; }
function writeConnection(connection) { const d=readData(); if(connection)d.gmail=connection;else delete d.gmail; writeData(d); }
function processedIds() { const d=readData(); return new Set(Array.isArray(d.gmailProcessedIds)?d.gmailProcessedIds:[]); }
function markProcessed(id,detail={}) { const d=readData(), ids=Array.isArray(d.gmailProcessedIds)?d.gmailProcessedIds:[]; if(!ids.includes(id))ids.unshift(id); d.gmailProcessedIds=ids.slice(0,3000); const events=Array.isArray(d.gmailEvents)?d.gmailEvents:[]; events.unshift({messageId:id,at:new Date().toISOString(),...detail}); d.gmailEvents=events.slice(0,1000); writeData(d); }

async function exchangeCode(code) { const body=new URLSearchParams({code,client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET,redirect_uri:process.env.GMAIL_REDIRECT_URI,grant_type:"authorization_code"}); const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}); const data=await response.json(); if(!response.ok)throw new Error(data.error_description||data.error||"Google no pudo completar la autorización"); return data; }
async function accessToken() { const connection=readConnection(); if(!connection?.refreshToken)throw new Error("Gmail todavía no está conectado"); const body=new URLSearchParams({client_id:process.env.GMAIL_CLIENT_ID,client_secret:process.env.GMAIL_CLIENT_SECRET,refresh_token:decryptSecret(connection.refreshToken),grant_type:"refresh_token"}); const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}); const data=await response.json(); if(!response.ok||!data.access_token)throw new Error(data.error_description||data.error||"No se pudo renovar el acceso a Gmail"); return data.access_token; }
async function gmailApi(resource,token) { const response=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/"+resource,{headers:{Authorization:"Bearer "+token}}),data=await response.json(); if(!response.ok)throw new Error(data.error?.message||"Error de Gmail"); return data; }
function decode64(value){return Buffer.from(String(value||"").replace(/-/g,"+").replace(/_/g,"/"),"base64").toString("utf8");}
function extractBody(payload){if(!payload)return"";if(payload.body?.data)return decode64(payload.body.data);const parts=Array.isArray(payload.parts)?payload.parts:[];for(const type of ["text/plain","text/html"]){const part=parts.find(i=>i.mimeType===type&&i.body?.data);if(part)return decode64(part.body.data).replace(/<[^>]+>/g," ");}for(const part of parts){const text=extractBody(part);if(text)return text;}return"";}
function header(payload,name){return(payload?.headers||[]).find(i=>String(i.name||"").toLowerCase()===name.toLowerCase())?.value||"";}
async function listMessages(token){const q=encodeURIComponent("from:noreply@claimservices.com.ar newer_than:2d"),data=await gmailApi(`messages?q=${q}&maxResults=50`,token);return Array.isArray(data.messages)?data.messages:[];}
async function message(token,id){return gmailApi(`messages/${encodeURIComponent(id)}?format=full`,token);}
function activeBaseFor(address){const text=String(address||"").toLowerCase(),active=basesDoc.bases.filter(i=>i.estado==="ACTIVO"),exact=active.find(i=>text.includes(String(i.base||"").toLowerCase()));if(exact)return exact;const province=active.find(i=>text.includes(String(i.zona||"").toLowerCase()));if(province)return province;const interior=/mendoza|cordoba|córdoba|santa fe|entre rios|entre ríos|misiones|chaco|salta|tucuman|tucumán|la pampa|santa cruz/i.test(text);return active.find(i=>i.modalidad===(interior?"INTERIOR":"AMBA_CABA"))||active[0];}
async function geocode(address){const key=process.env.GOOGLE_MAPS_API_KEY;if(!key)throw new Error("Google Maps no configurado");const url=new URL("https://maps.googleapis.com/maps/api/geocode/json");url.searchParams.set("address",address);url.searchParams.set("region","ar");url.searchParams.set("key",key);const response=await fetch(url),data=await response.json();if(!response.ok||data.status!=="OK"||!data.results?.[0])throw new Error("No se pudo localizar "+address);return data.results[0].geometry.location;}
async function routeKm(origin,destination){const response=await fetch("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":process.env.GOOGLE_MAPS_API_KEY,"X-Goog-FieldMask":"routes.distanceMeters"},body:JSON.stringify({origin:{location:{latLng:{latitude:origin.lat,longitude:origin.lng}}},destination:{location:{latLng:{latitude:destination.lat,longitude:destination.lng}}},travelMode:"DRIVE",routingPreference:"TRAFFIC_UNAWARE"})}),data=await response.json(),meters=data.routes?.[0]?.distanceMeters;if(!response.ok||!Number.isFinite(meters))throw new Error(data.error?.message||"No se pudo calcular recorrido");return Math.round((meters/1000)*10)/10;}
function runtimeApi(port){const origin=`http://127.0.0.1:${port}`;let token=null;async function login(){const response=await fetch(origin+"/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:process.env.ADMIN_USER||"admin",password:process.env.ADMIN_PASSWORD||""})}),data=await response.json();if(!response.ok||!data.token)throw new Error("No se pudo autenticar la automatización interna");token=data.token;}return async function api(route,options={}){if(!token)await login();const headers={...(options.headers||{}),Authorization:"Bearer "+token};let response=await fetch(origin+route,{...options,headers});if(response.status===401){await login();headers.Authorization="Bearer "+token;response=await fetch(origin+route,{...options,headers});}const data=await response.json();if(!response.ok)throw new Error(data.error||"Error de API interna");return data;};}
async function distances(parsed,base){const modality=base.modalidad==="INTERIOR"?"INTERIOR":"AMBA_CABA";let baseOrigin=0,originDestination=0,destinationBase=0;try{const baseCoord=await geocode([base.base,base.zona,"Argentina"].filter(Boolean).join(", ")),originCoord=await geocode(parsed.origen+", Argentina");baseOrigin=await routeKm(baseCoord,originCoord);if(parsed.destino&&parsed.tipoServicio!=="Auxilio mecanico"){const destinationCoord=await geocode(parsed.destino+", Argentina");originDestination=await routeKm(originCoord,destinationCoord);if(modality==="INTERIOR")destinationBase=await routeKm(destinationCoord,baseCoord);}}catch(error){console.warn("[Asistir24 Gmail] Distancias pendientes",parsed.asistenciaId,error.message);}return{modality,baseOrigin,originDestination,destinationBase};}

function install({app,port}){
  if(!app)throw new Error("No se pudo capturar Express");
  function requireAdmin(req,res){try{const h=req.headers.authorization||"",d=jwt.verify(h.startsWith("Bearer ")?h.slice(7):"",jwtSecret());if(d.role!=="admin"){res.status(403).json({error:"Acceso exclusivo para administradores"});return null;}return d;}catch{res.status(401).json({error:"No autorizado"});return null;}}
  app.get("/api/gmail/status",async(req,res)=>{if(!requireAdmin(req,res))return;const c=readConnection(),result={configured:gmailConfigured(),connected:Boolean(c?.refreshToken),email:c?.email||null,connectedAt:c?.connectedAt||null,autoEnabled:GMAIL_AUTO_ENABLED,pollMs:GMAIL_POLL_MS};if(result.connected&&gmailConfigured()){try{const t=await accessToken(),p=await gmailApi("profile",t);result.email=p.emailAddress||result.email;result.verified=true;}catch(e){result.verified=false;result.error=e.message;}}res.json(result);});
  app.get("/api/gmail/oauth/start",(req,res)=>{const d=requireAdmin(req,res);if(!d)return;if(!gmailConfigured())return res.status(503).json({error:"Faltan variables OAuth de Gmail en Railway"});const state=jwt.sign({purpose:"gmail-oauth",user:d.user},jwtSecret(),{expiresIn:"10m"}),url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",process.env.GMAIL_CLIENT_ID);url.searchParams.set("redirect_uri",process.env.GMAIL_REDIRECT_URI);url.searchParams.set("response_type","code");url.searchParams.set("scope",GMAIL_SCOPE);url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");url.searchParams.set("include_granted_scopes","true");url.searchParams.set("login_hint",GMAIL_EXPECTED_ACCOUNT);url.searchParams.set("state",state);res.json({authorizationUrl:url.toString(),account:GMAIL_EXPECTED_ACCOUNT});});
  app.get("/api/gmail/oauth/callback",async(req,res)=>{try{if(req.query.error)throw new Error("Google rechazó la autorización: "+req.query.error);const code=String(req.query.code||""),state=String(req.query.state||"");if(!code||!state)throw new Error("Faltan datos de autorización");const d=jwt.verify(state,jwtSecret());if(d.purpose!=="gmail-oauth")throw new Error("Estado OAuth inválido");const tokens=await exchangeCode(code),profile=await gmailApi("profile",tokens.access_token),email=String(profile.emailAddress||"").toLowerCase();if(GMAIL_EXPECTED_ACCOUNT&&email!==GMAIL_EXPECTED_ACCOUNT.toLowerCase())throw new Error("Se autorizó "+email+", pero debe conectarse "+GMAIL_EXPECTED_ACCOUNT);const previous=readConnection(),refreshToken=tokens.refresh_token?encryptSecret(tokens.refresh_token):previous?.refreshToken;if(!refreshToken)throw new Error("Google no devolvió refresh token");writeConnection({email,refreshToken,scope:tokens.scope||GMAIL_SCOPE,connectedAt:new Date().toISOString(),connectedBy:d.user||"admin"});res.redirect("/admin?gmail=connected");setTimeout(()=>poll().catch(()=>{}),1000);}catch(error){console.error("[Asistir24 Gmail] OAuth:",error.message);res.status(400).send("No se pudo conectar Gmail: "+error.message);}});
  app.post("/api/gmail/disconnect",(req,res)=>{if(!requireAdmin(req,res))return;writeConnection(null);res.json({success:true});});
  app.post("/api/gmail/sync",async(req,res)=>{if(!requireAdmin(req,res))return;try{res.json({success:true,...await poll()});}catch(error){res.status(400).json({error:error.message});}});

  const api=runtimeApi(port);let running=false;
  async function poll(){if(running)return{skipped:true};if(!gmailConfigured()||!readConnection()?.refreshToken)return{connected:false};running=true;let processed=0,quoted=0,confirmed=0;try{const token=await accessToken(),refs=await listMessages(token),seen=processedIds();for(const ref of refs.reverse()){if(seen.has(ref.id))continue;try{const msg=await message(token,ref.id),subject=header(msg.payload,"Subject"),body=extractBody(msg.payload),parsed=parseClaimsMail({messageId:msg.id,threadId:msg.threadId,subject,body});if(!parsed.asistenciaId){markProcessed(ref.id,{evento:"REVISAR",subject,motivo:"Sin ID Asistencia"});processed++;continue;}if(parsed.evento==="COTIZAR"){const quotes=await api("/api/cotizaciones"),exists=quotes.items.some(i=>String(i.numeroServicio)===String(parsed.asistenciaId));if(!exists){const base=activeBaseFor(parsed.origen);if(!base)throw new Error("No hay base activa disponible");const d=await distances(parsed,base);await api("/api/cotizar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tipoCliente:"COMPANIA",empresa:parsed.empresa||"Compañía",numeroServicio:parsed.asistenciaId,patente:parsed.patente,baseId:base.id,modalidad:d.modality,tipoServicio:parsed.tipoServicio||"Liviano",origen:parsed.origen,destino:parsed.destino,kmBaseOrigen:d.baseOrigin,kmOrigenDestino:parsed.tipoServicio==="Auxilio mecanico"?0:d.originDestination,kmDestinoBase:d.modality==="INTERIOR"&&parsed.tipoServicio!=="Auxilio mecanico"?d.destinationBase:0})});quoted++;}markProcessed(ref.id,{evento:"COTIZAR",asistenciaId:parsed.asistenciaId,subject});}else if(parsed.evento==="CONFIRMACION"){const quotes=await api("/api/cotizaciones"),quote=quotes.items.find(i=>String(i.numeroServicio)===String(parsed.asistenciaId));if(quote&&!['LISTO_PARA_WHATSAPP','ENVIADO_WHATSAPP','EN_SERVICIO','FINALIZADO'].includes(quote.flujo?.estado)){await api(`/api/cotizaciones/${encodeURIComponent(quote.id)}/confirmar`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({detalle:"Confirmación recibida automáticamente desde Gmail"})});confirmed++;}markProcessed(ref.id,{evento:"CONFIRMACION",asistenciaId:parsed.asistenciaId,subject});}else markProcessed(ref.id,{evento:"REVISAR",asistenciaId:parsed.asistenciaId,subject});processed++;}catch(error){console.error("[Asistir24 Gmail] Mensaje",ref.id,error.message);}}return{processed,quoted,confirmed};}finally{running=false;}}
  if(GMAIL_AUTO_ENABLED){setTimeout(()=>poll().catch(e=>console.error("[Asistir24 Gmail] Inicio:",e.message)),5000);setInterval(()=>poll().catch(e=>console.error("[Asistir24 Gmail] Poll:",e.message)),GMAIL_POLL_MS).unref();}
  return{poll};
}
module.exports={install};
