const CLAIMS_BASES = require("../data/claims-bases.json");

function patchLocationApi(source) {
  if (source.includes('app.post("/api/ruta-completa"')) return source;
  const marker = 'app.post("/api/distancia", auth, async (req, res) => {';
  if (!source.includes(marker)) return source;

  // Bases exactas confirmadas por Operaciones. Se aplican al cargar server.js,
  // antes de exponer /api/bases y antes de calcular cualquier recorrido.
  const claimsBasesBootstrap = [
    'const CLAIMS_BASES_FIJAS = ' + JSON.stringify(CLAIMS_BASES) + ';',
    'function normClaims(v){ return String(v || "").normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }',
    'function claimsBaseMatch(base){ const bp=normClaims(base?.prestador), bl=normClaims(base?.base); return CLAIMS_BASES_FIJAS.find(x => { const xp=normClaims(x.prestador), xl=normClaims(x.localidad); return (bp.includes(xp) || xp.includes(bp)) && (bl.includes(xl) || xl.includes(bl)); }); }',
    'for (const fija of CLAIMS_BASES_FIJAS) {',
    '  const match = basesDoc.bases.find(b => { const bp=normClaims(b.prestador), bl=normClaims(b.base); const fp=normClaims(fija.prestador), fl=normClaims(fija.localidad); return (bp.includes(fp) || fp.includes(bp)) && (bl.includes(fl) || fl.includes(bl)); });',
    '  const modalidad = /^(CABA|NORTE|OESTE|SUR)$/i.test(fija.zona) ? "AMBA_CABA" : "INTERIOR";',
    '  const direccionCompleta = [fija.direccion, fija.localidad, fija.zona, "Argentina"].filter(Boolean).join(", ");',
    '  if (match) { match.direccion = direccionCompleta; match.direccionFijaClaims = true; match.modalidad = modalidad; }',
    '}',
    ''
  ].join('\n');

  const exactBasesBootstrap = [
    'const BASES_EXACTAS_OPERACIONES = [',
    '  { id: "mm-remolques-saenz-pena", match: b => b.prestador === "MM Remolques", prestador: "MM Remolques", base: "Sáenz Peña", direccion: "Gral. Enrique Mosconi 2535, Sáenz Peña, Tres de Febrero, Buenos Aires, Argentina", zona: "ZONA OESTE", modalidad: "AMBA_CABA", estado: "ACTIVO", tipo: "Semipesados" },',
    '  { id: "ryj-manuel-alberti", match: b => b.prestador === "Remolques R y J" && b.id === "ryj-del-viso", prestador: "Remolques R y J", base: "Manuel Alberti", direccion: "Los Gladiolos 1179, Manuel Alberti, Pilar, Buenos Aires, Argentina", zona: "ZONA NORTE", modalidad: "AMBA_CABA", estado: "ACTIVO", tipo: "Semipesado" },',
    '  { id: "gruas-auxilio-russo-siquiman", match: b => b.id === "nahuel-ruso-parque-siguiman", prestador: "Grúas y Auxilio Russo", base: "Villa Parque Síquiman", direccion: "Av. Perón, Villa Parque Síquiman, Córdoba, Argentina", zona: "CORDOBA", modalidad: "INTERIOR", estado: "ACTIVO", tipo: "Semipesado" },',
    '  { id: "marco-del-viso", match: b => b.id === "marcos-del-viso", prestador: "Marco", base: "Del Viso", direccion: "Agustín Álvarez 5756, Del Viso, Pilar, Buenos Aires, Argentina", zona: "ZONA NORTE", modalidad: "AMBA_CABA", estado: "ACTIVO", tipo: "Semipesado" },',
    '  { id: "moises-beiro-gral-paz", match: b => b.id === "moises-beiro-gral-paz", prestador: "Moisés", base: "Beiró y General Paz", direccion: "Av. Francisco Beiró y Av. General Paz, Ciudad Autónoma de Buenos Aires, Argentina", zona: "CABA", modalidad: "AMBA_CABA", estado: "ACTIVO", tipo: "Semipesados" },',
    '  { id: "gruas-andres-berazategui", match: b => b.id === "gruas-andres-berazategui", prestador: "Grúas Andrés", base: "Berazategui", direccion: "Calle 205 311, Berazategui, Buenos Aires, Argentina", zona: "ZONA SUR", modalidad: "AMBA_CABA", estado: "ACTIVO", tipo: "Semipesado" }',
    '];',
    'for (const exacta of BASES_EXACTAS_OPERACIONES) {',
    '  const index = basesDoc.bases.findIndex(exacta.match);',
    '  const limpia = { id: exacta.id, prestador: exacta.prestador, base: exacta.base, direccion: exacta.direccion, zona: exacta.zona, modalidad: exacta.modalidad, estado: exacta.estado, tipo: exacta.tipo };',
    '  if (index >= 0) basesDoc.bases[index] = { ...basesDoc.bases[index], ...limpia };',
    '  else basesDoc.bases.push(limpia);',
    '}',
    ''
  ].join('\n');

  const endpoint = [
    'const CENTROS_BASE_PROVISORIOS = {',
    '  "eugenio-casanova": [-34.700, -58.585], "eugenio-liniers": [-34.643, -58.520], "federico-escobar": [-34.346, -58.794],',
    '  "ariel-sys-zarate-belgrano": [-34.095, -59.024], "ariel-sys-mar-de-ajo": [-36.724, -56.678], "ulises-villa-tesei": [-34.621, -58.633],',
    '  "lucas-moreno": [-34.650, -58.790], "mm-remolques-devoto": [-34.603, -58.513], "mm-remolques-saenz-pena": [-34.599, -58.527],',
    '  "eugenio-lomas-zamora": [-34.761, -58.403], "agustin-varela": [-34.796, -58.276], "supercharge-la-plata": [-34.921, -57.954],',
    '  "marcos-del-viso": [-34.451, -58.806], "marco-del-viso": [-34.469, -58.794], "sergio-duran-la-plata": [-34.921, -57.954],',
    '  "gruas-andres-berazategui": [-34.802, -58.230], "hernan-becerra-garin": [-34.426, -58.737], "ryj-del-viso": [-34.451, -58.806],',
    '  "ryj-manuel-alberti": [-34.507, -58.782], "ryj-pilar": [-34.459, -58.914], "andres-mar-del-plata": [-38.005, -57.542],',
    '  "gruas-dany-villa-dominico": [-34.689, -58.319], "lucas-junin": [-34.585, -60.949], "aux-suburbano-pinamar": [-37.114, -56.861],',
    '  "aux-suburbano-mar-del-plata": [-38.005, -57.542], "aux-suburbano-mar-de-ajo": [-36.724, -56.678], "martin-intrepido-jose-c-paz": [-34.523, -58.774],',
    '  "martin-garupa": [-27.483, -55.829], "lucas-grua-jose-leon-suarez": [-34.534, -58.575], "alfredo-mercado-salta": [-24.783, -65.411],',
    '  "fernando-tucuman": [-26.831, -65.204], "auxchek-parana": [-31.741, -60.511], "ldv-valentin-alsina": [-34.674, -58.416],',
    '  "el-misio-florencio-varela": [-34.796, -58.276], "eugenio-don-torcuato": [-34.494, -58.639], "gabriel-fenix-olavarria": [-36.892, -60.323],',
    '  "remolques-la-familia-la-pampa": [-36.620, -64.291], "charly-caba": [-34.604, -58.382], "juliano-mendoza": [-32.890, -68.845],',
    '  "marcos-pilar": [-34.459, -58.914], "jesus-la-pampa": [-36.620, -64.291], "auxilios-diaz-mendoza": [-32.890, -68.845],',
    '  "sebastina-ezeiza": [-34.854, -58.522], "el-bocha-virrey-del-pino": [-34.848, -58.681], "remolques-nahuel-zarate": [-34.095, -59.024],',
    '  "aux-asist-caseros": [-34.603, -58.563], "nahuel-san-miguel": [-34.543, -58.712], "gruas-tummsa-el-pato": [-34.879, -58.171],',
    '  "gruas-tummsa-castelli": [-36.091, -57.807], "nahuel-ruso-parque-siguiman": [-31.343, -64.480], "gruas-auxilio-russo-siquiman": [-31.343, -64.480],',
    '  "miriam-aux-canals": [-33.565, -62.889], "remolques-tito-constitucion": [-33.233, -60.329], "javy-burzaco": [-34.829, -58.394],',
    '  "david-iocco-rosario": [-32.958, -60.693], "oscar-bahia-blanca": [-38.719, -62.266], "palo-humadera-quilmes": [-34.721, -58.254],',
    '  "daniel-saenz-pena": [-26.790, -60.442], "guevara-hijos-la-plata": [-34.921, -57.954], "gallardo-rio-gallegos": [-51.623, -69.216],',
    '  "auxleo-mendoza": [-32.890, -68.845], "moises-beiro-gral-paz": [-34.590, -58.520]',
    '};',
    'function centroBase(base) {',
    '  const value = CENTROS_BASE_PROVISORIOS[base?.id];',
    '  return Array.isArray(value) ? { lat: value[0], lng: value[1], provider: "Centro provisorio" } : null;',
    '}',
    'function tipoBaseCompatible(base, tipoServicio) {',
    '  const solicitado = String(tipoServicio || "").toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g, "");',
    '  const disponible = String(base?.tipo || "").toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g, "");',
    '  if (!solicitado) return true;',
    '  if (solicitado.includes("auxilio")) return disponible.includes("aux") || disponible.includes("moto");',
    '  if (solicitado.includes("moto")) return disponible.includes("moto") || disponible.includes("aux");',
    '  if (solicitado.includes("semi") || solicitado.includes("liviano")) return disponible.includes("semi") || disponible.includes("grua") || disponible.includes("tenedor");',
    '  return true;',
    '}',
    'app.post("/api/base-mas-cercana", auth, async (req, res) => {',
    '  try {',
    '    const origenTexto = String(req.body?.origen || "").trim();',
    '    const tipoServicio = String(req.body?.tipoServicio || "").trim();',
    '    if (!origenTexto) return res.status(400).json({ error: "Ingrese la geolocalización de Claims" });',
    '    const origenCoord = await geocodeTomTom(origenTexto);',
    '    const candidatas = basesDoc.bases.filter(base => base.estado === "ACTIVO" && tipoBaseCompatible(base, tipoServicio));',
    '    const resultados = [];',
    '    for (let i = 0; i < candidatas.length; i += 8) {',
    '      const lote = candidatas.slice(i, i + 8);',
    '      const parcial = await Promise.all(lote.map(async base => {',
    '        try {',
    '          const texto = base.direccion || [base.base, base.zona, "Argentina"].filter(Boolean).join(", ");',
    '          const coord = centroBase(base) || await geocodeTomTom(texto);',
    '          const rad = Math.PI / 180;',
    '          const dLat = (coord.lat - origenCoord.lat) * rad;',
    '          const dLng = (coord.lng - origenCoord.lng) * rad;',
    '          const a = Math.sin(dLat/2) ** 2 + Math.cos(origenCoord.lat*rad) * Math.cos(coord.lat*rad) * Math.sin(dLng/2) ** 2;',
    '          return { base, coord, lineaRecta: 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)) };',
    '        } catch { return null; }',
    '      }));',
    '      resultados.push(...parcial.filter(Boolean));',
    '    }',
    '    const preseleccion = resultados.sort((a,b) => a.lineaRecta - b.lineaRecta).slice(0, 3);',
    '    if (!preseleccion[0]) return res.status(404).json({ error: "No hay una base activa compatible para este servicio" });',
    '    res.json({ success: true, origen: origenCoord, recomendada: { ...preseleccion[0].base, kmAproximada: Math.round(preseleccion[0].lineaRecta*10)/10 }, alternativas: preseleccion.slice(1,3).map(x => ({ ...x.base, kmAproximada: Math.round(x.lineaRecta*10)/10 })) });',
    '  } catch (error) {',
    '    res.status(503).json({ error: error.message || "No se pudo seleccionar la base más cercana" });',
    '  }',
    '});',
    '',
    'app.post("/api/ruta-completa", auth, async (req, res) => {',
    '  try {',
    '    const base = basesDoc.bases.find(item => item.id === req.body?.baseId);',
    '    const origenTexto = String(req.body?.origen || "").trim();',
    '    const destinoTexto = String(req.body?.destino || "").trim();',
    '    const modalidad = req.body?.modalidad === "INTERIOR" ? "INTERIOR" : (base?.modalidad === "INTERIOR" ? "INTERIOR" : "AMBA_CABA");',
    '    const auxilio = String(req.body?.tipoServicio || "").toLowerCase().replace(/á/g, "a") === "auxilio mecanico";',
    '    if (!base) return res.status(400).json({ error: "Base inválida" });',
    '    if (!origenTexto) return res.status(400).json({ error: "Ingrese la ubicación de origen" });',
    '    if (!auxilio && !destinoTexto) return res.status(400).json({ error: "Ingrese el destino" });',
    '    const baseTexto = base.direccion || [base.base, base.zona, "Argentina"].filter(Boolean).join(", ");',
    '    const [baseCoord, origenCoord] = await Promise.all([Promise.resolve(centroBase(base)).then(value => value || geocodeTomTom(baseTexto)), geocodeTomTom(origenTexto)]);',
    '    const baseOrigen = await routeKmTomTom(baseCoord, origenCoord);',
    '    let origenDestino = 0;',
    '    let destinoBase = 0;',
    '    let destinoCoord = null;',
    '    if (!auxilio) {',
    '      destinoCoord = await geocodeTomTom(destinoTexto);',
    '      origenDestino = await routeKmTomTom(origenCoord, destinoCoord);',
    '      if (modalidad === "INTERIOR") destinoBase = await routeKmTomTom(destinoCoord, baseCoord);',
    '    }',
    '    res.json({',
    '      success: true, modalidad, auxilio, baseDireccion: baseTexto,',
    '      tramos: { baseOrigen, origenDestino, destinoBase },',
    '      kmTotal: Math.round((baseOrigen + origenDestino + destinoBase) * 10) / 10,',
    '      coordenadas: { base: baseCoord, origen: origenCoord, destino: destinoCoord }',
    '    });',
    '  } catch (error) {',
    '    res.status(503).json({ error: error.message || "No se pudo calcular el recorrido", mapsFallback: true });',
    '  }',
    '});',
    ''
  ].join('\n');
  return source.replace(marker, claimsBasesBootstrap + exactBasesBootstrap + endpoint + marker);
}
module.exports = { patchLocationApi };
